{{- if .Values.hawkular }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.applicationName }}-zookeeper-hawkular-config
  labels:
    component: zookeeper
    role: metrics
    {{- include "standardLabels" . | indent 4 }}
data:
  hawkular-openshift-agent: |
    endpoints:
    - type: jolokia
      protocol: https
      port: 8778
      path: /jolokia/
      collection_interval: 30s
      tls:
        skip_certificate_validation: true
      credentials:
        username: secret:{{ .Values.global.applicationName }}-jolokia-sercret/username
        password: secret:{{ .Values.global.applicationName }}-jolokia-sercret/password
      metrics:
      - name: java.lang:type=Memory#HeapMemoryUsage#used
        type: gauge
        id: jvm.heap.used
        units: B
        tags:
          jvm_metrics: true
          jvm_heap: true
{{- end }}