apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    component: zookeeper
    {{- include "standardLabels" . | indent 4 }}
spec:
  ports:
  - port: 2181
    name: client
  selector:
    component: zookeeper
    {{- include "standardLabels" . | indent 4 }}
