{{- if .Values.hawkular }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.applicationName }}-kafka-hawkular-config
  labels:
    component: kafka-broker
    role: metrics
    {{- include "standardLabels" . | indent 4 }}
data:
  hawkular-openshift-agent: |
    endpoints:
    - type: jolokia
      protocol: https
      port: 8778
      path: /jolokia/
      collection_interval: 30s
      tls:
        skip_certificate_validation: true
      credentials:
        username: secret:{{ .Values.global.applicationName }}-jolokia-sercret/username
        password: secret:{{ .Values.global.applicationName }}-jolokia-sercret/password
      metrics:
      - name: kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec,topic=*#OneMinuteRate
        type: gauge
        id: kafka.${topic}.BytesInPerSec.rate
        description: ${topic} BytesInPerSec rate (1min)
        tags:
          topic_metrics: true
          byte_rate: true
          input: true
      - name: kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec,topic=*#OneMinuteRate
        type: gauge
        id: kafka.${topic}.BytesOutPerSec.rate
        description: ${topic} BytesOutPerSec rate (1min)
        tags:
          topic_metrics: true
          byte_rate: true
          output: true
      - name: kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec,topic=*#OneMinuteRate
        type: gauge
        id: kafka.${topic}.MessageInPerSec.rate
        description: ${topic} ${name} (1min)
        tags:
          topic_metrics: true
          message_rate: true
      - name: java.lang:type=Memory#HeapMemoryUsage#used
        type: gauge
        id: jvm.heap.used
        units: B
        tags:
          jvm_metrics: true
          jvm_heap: true
{{- end }}